[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "code-query"
version = "0.1.0"
description = "code query"
dependencies = [
    "qdrant-client",
    "openai",
    "tiktoken",
    "python-dotenv"
]

[project.scripts]
cq = "cq.cli:main"

[tool.setuptools.packages.find]
include = ["cq"]
